### ISSUE TITLE
Support persistent pilots, guests, and guilds

### ISSUE THREAD

**Issue by chuuwee** [chuuwee/lineage#14]
No need to specify every tick. Note them whenever you can, and have them captured in the subsequent tick.

The only time you'll need to note anything is when you're absent.

**Comment by Checkyekian** [comment]
Frequent confusion on whether or not bot drivers or people under different names are being captured. Hopefully, this will fix that issue, and no longer have the script taker be responsible for other people's responsibilities.

**Comment by chuuwee** [comment]
Resolved this one in or prior to 0.2.1
